services:
  postgres:
    image: postgres:16.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
